"""
Configuration module for the RAG application.
"""

from config.constants import (
    EN, VI, NONE, USER, ASSISTANT, ENGLISH, VIETNAMESE,
    LANGCHAIN_LLM, DEFAULT_LANGCHAIN_MODEL, DEFAULT_LANGCHAIN_PROVIDER,
    DB, VECTOR_SEARCH, LANGCHAIN_PROVIDERS, OLLAMA_MODELS,
    DEFAULT_CHUNK_SIZE, DEFAULT_CHUNK_OVERLAP, DEFAULT_NUM_DOCS_RETRIEVAL,
    MODEL_TYPES, NO_CHUNKING, RECURSIVE_CHUNKER, SEMANTIC_CHUNKER, AGENTIC_CHUNKER,
    UPLOAD
)